### ISSUE TITLE
Inicio de sesión error

### ISSUE THREAD

**Issue by JefferGonzalez** [pheralb/slug#18]
Hola, reciénteme he tratado de acceder a tu aplicación, pero al momento de iniciar sesión no redirecciona correctamente. 

https://github.com/pheralb/slug/assets/86365947/39dad362-a703-4947-9b51-1eecb647a2b7

**Comment by Hyuuh** [comment]
Hola, @JefferGonzalez.
Resulta que @pheralb estaba realizando modificaciones a la rama next 09cd5c426e1e8ee4f5db231c96967372ac02ffbf, y está usando la misma app de OAuth de GitHub en la de next, entonces te redireccionaba al localhost. Disculpa las molestias.
